name = "domain_core"
version = "1.0.0"
target = "javascript"

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_javascript = ">= 0.8.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
